name: DRAW.IO EXPORT

on:
  workflow_call:
    inputs:
      drawio_path:
        description: 'Path where drawio diagrams are stored'
        default: "."
        required: false
        type: string
      drawio_png_format_export_path:
        description: 'Path where png files should be exported (relative to drawio_path)'
        type: string
        required: false
        default: "export"
      drawio_svg_format_export_path:
        description: 'Path where svg files should be exported (relative to drawio_path). If empty, no svg files will be exported.'
        default: "export/svg"
        required: false
        type: string
      drawio_export_as_png:
        description: 'Export drawio files as png'
        default: true
        required: false
        type: boolean
      drawio_export_as_svg:
        description: 'Export drawio files as svg'
        default: false
        required: false
        type: boolean
      drawio_action_mode:
        description: 'Action mode to use for drawio-export-action (default: "all")'
        default: 'all'
        required: false
        type: string
      commit_user:
        description: 'Username which should be used for commits by github action'
        default: 'github-actions'
        required: false
        type: string
      commit_email:
        description: 'Email which should be used for commits by github action'
        default: 'noreply@github.com'
        required: false
        type: string
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Make Sure Required 'GH_APP_ID' and 'GH_APP_PRIVATE_KEY' Secrets are Available
        shell: bash
        run: |
          if [[ -z "${{ secrets.GH_APP_ID }}" || -z "${{ secrets.GH_APP_PRIVATE_KEY }}" ]]; then
            echo "Error: Required secrets 'GH_APP_ID' and 'GH_APP_PRIVATE_KEY' are not set."
            exit 1
          fi

      - name: Get Github Access Token
        id: github_app_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          # if owner and repositories are empty, access will be scoped to only the current repository
          owner: ''
          repositories: ''

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.github_app_token.outputs.token }}

      - name: Export drawio files to asciidoctor and png files
        uses: rlespinasse/drawio-export-action@v2
        if: ${{ inputs.drawio_export_as_png == true }}
        with:
          path: ${{ inputs.drawio_path }}
          output: ${{ inputs.drawio_png_format_export_path }}
          format: png
          transparent: false
          action-mode: ${{ inputs.drawio_action_mode }}
          remove-page-suffix: true
          scale: 2
          quality: 95
          uncompressed: true

      - name: Export drawio files to svg files
        uses: rlespinasse/drawio-export-action@v2
        if: ${{ inputs.drawio_export_as_svg == true }}
        with:
          path: ${{ inputs.drawio_path }}
          output: ${{ inputs.drawio_svg_format_export_path }}
          format: svg
          transparent: false
          action-mode: ${{ inputs.drawio_action_mode }}
          remove-page-suffix: true
          scale: 2
          quality: 95
          uncompressed: true

      - name: Commit Changes
        run: |
          git config --local user.name "${{ inputs.commit_user }}"
          git config --local user.email "${{ inputs.commit_email }}"
          git add .
          if [[ -z $(git status -s) ]]; then
            echo "diff=false" >> $GITHUB_OUTPUT
          else
            echo "diff=true" >> $GITHUB_OUTPUT
          fi
          git diff-index --quiet HEAD || git commit -m "docs: sync draw.io exported files" -a

      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ steps.github_app_token.outputs.token }}
          branch: ${{ github.ref }}