name: HUGO BUILD

on:
  workflow_call:
    secrets:
      GH_SA_TOKEN_RO:
        required: true

jobs:
  hugo-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Page
        run: hugo --minify

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GH_SA_TOKEN_RO }}
          enforce_admins: false
          branch: gh-pages

      - name: Deploy Page
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GH_SA_TOKEN_RO }}
          publish_dir: ./public
          cname: nuvibit.com

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GH_SA_TOKEN_RO }}
          enforce_admins: true
          branch: gh-pages
